### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by kendaleiv** [johnstaveley/SecurityEssentials#10]
Can you add a license to this repository?

I'm interested in the https://github.com/johnstaveley/SecurityEssentials/blob/master/Tests/Unit/Web.Unit.Tests/Controllers/ValidateAntiForgeryTokenTest.cs logic to detect when `[IgnoreAntiforgeryToken]` has been unexpectedly checked in.

**Comment by johnstaveley** [comment]
Your free to use as you wish. Is this what you need? If not what license would you prefer.

Also I don't recognise IgnoreAntiforgeryToken

**Comment by kendaleiv** [comment]
Thanks! I was looking to validate something with ASP.NET Core, thanks for the reference!
