### ISSUE TITLE
PostgresSQL :: Feature request

### ISSUE THREAD

**Issue by ghost** [johnstaveley/SecurityEssentials#12]
Hi @johnstaveley ,

Requesting feature PostgreSQL as a database option.

```
"ConnectionStrings": {
    "DefaultConnection": ""
},
"NetCoreTemplate": {
    "DatabaseProvider": "PostgresSQL"
}
```

**Comment by johnstaveley** [comment]
Hi, this is a template with enhanced security features.  It is intended to be a base Mvc project with a higher baseline in security than the one Microsoft give you. Unless it is a specific security feature with general appeal I won't include it in the template. The request you have above you can make by forking this project and adding it into your solution. It does not need to appear in every template. Thanks for your interest in security essentials

**Comment by ghost** [comment]
Thanks @johnstaveley   for your response.
