### ISSUE TITLE
AspNetCore 2.2 :: Feature request

### ISSUE THREAD

**Issue by ghost** [johnstaveley/SecurityEssentials#13]
Hi @johnstaveley ,

Is this template compatible with aspnetcore 2.2 if not do have a version of this template which is using aspnetcore 2.2?

**Comment by ghost** [comment]
Also do you have any intentions of converting this project to MVC5

**Comment by johnstaveley** [comment]
I don't know if it is compatible, have you tried? Also, this:
<package id="Microsoft.AspNet.Mvc" version="5.2.7" targetFramework="net461" />

**Comment by ghost** [comment]
What do mean by "also this:"?

I will be trying to convert this project to aspnetcore tonight but would be cool if it was upgraded to mvc 5

**Comment by johnstaveley** [comment]
HI, the project is in Mvc 5 as indicated by the package number. I understand the razor syntax has changed for core. Let me know how you get on

**Comment by johnstaveley** [comment]
Oh, I see! the git editor stripped out my copy/paste of the package number: package id="Microsoft.AspNet.Mvc" version="5.2.7" targetFramework="net461"

**Comment by ghost** [comment]
:+1: I will keep you updated.

**Comment by ghost** [comment]
Hi @johnstaveley unfortunately converting this application to aspnetcore is a mission but if you ever decide to create a template on this as aspnetcore please mention me here.

Its a standard now days as there is a a lot of developers are using aspnetcore and I cannot find any good templates with security implementations like your template.
