### ISSUE TITLE
Which license is this project under?

### ISSUE THREAD

**Issue by klingerts** [johnstaveley/SecurityEssentials#17]
Hi, I would like to use the 'AllowXRequestsEveryXSecondsAttribute', but the repo has no license.
Is the code in this project free and open source? If so, where can I find the license?

**Comment by johnstaveley** [comment]
The code is free and open source. Help yourself.
If there is a particular license you would like to see, name it

**Comment by klingerts** [comment]
Hi @johnstaveley. MIT license would be good enough for us.
