### ISSUE TITLE
Obsolete FirefoxDriver ctor

### ISSUE THREAD

**Issue by feldrim** [johnstaveley/SecurityEssentials#3]
On class **Hooks** (`SecurityEssentials\Tests\Acceptance\Web.Acceptance.Tests\Steps\Hooks.cs`) line 30 I see this issue:

`'FirefoxDriver.FirefoxDriver(ICapabilities)' is obsolete: 'FirefoxDriver should not be constructed with a raw ICapabilities or DesiredCapabilities object. Use FirefoxOptions instead. This constructor will be removed in a future release.'`

**Comment by johnstaveley** [comment]
Now updated and possible to run with different drivers
