### ISSUE TITLE
ImageFormat on "Tests/Acceptance/Web.Acceptance.Tests/Steps/Hooks.cs"

### ISSUE THREAD

**Issue by feldrim** [johnstaveley/SecurityEssentials#4]
Since `ImageFormat` is obsolete, it should be converted to `ScreenshotImageFormat`. So it should be `ScreenshotImageFormat.Png`.

**Comment by johnstaveley** [comment]
Hi, you mean after upgrading Selenium. Yes, I have fixed, run regression and pushed the changes
