### ISSUE TITLE
Selenium implicitly wait

### ISSUE THREAD

**Issue by feldrim** [johnstaveley/SecurityEssentials#5]
Since ImplicitlyWait method used in `Tests/Acceptance/Web.Acceptance.Tests/Steps/Hooks.cs` is obsolete, the line

`webDriver.Manage().Timeouts().ImplicitlyWait(new TimeSpan(0, 0, 5));`

should be converted to

`webDriver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);`

**Comment by johnstaveley** [comment]
Hi, you mean after upgrading Selenium. Yes, I have fixed, run regression and pushed the changes
