### ISSUE TITLE
Implementing IDisposable

### ISSUE THREAD

**Issue by feldrim** [johnstaveley/SecurityEssentials#6]
Test classes contains disposable properties, which means those classes should also implement IDisposable. Because those properties managed in somewhere else codebase, adding

```
protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
                // Supressing IDisposable issue
            }
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        ~BaseControllerTest()
        {
            Dispose(false);
        }
```

to BaseControllerTest class would _probably_ be enough after implementation.

**Comment by johnstaveley** [comment]
Added in the code, sorry for the late response
