### ISSUE TITLE
How-to guide for existing apps

### ISSUE THREAD

**Issue by arc95** [johnstaveley/SecurityEssentials#8]
Thank you for creating this great app. I'm working to implement the security measures in an MVC project that's mostly complete but not yet in production. If starting from scratch, I'd use this as my baseline; however, for an existing project, what's a good approach to ensure all the measures in the app are implemented? 

The list in the read-me enumerates the security steps; but how are these implemented in the app? This can be as simple as links from the items in that list to specific files/lines in the source code on Github. I can then just go down the list and ensure my code follows these best practices.

Thank you.

**Comment by johnstaveley** [comment]
Hi, this deserves a thorough response however I'm on holiday at the moment with limited access to the internet. My starter for 10 would then be. Search the application for everywhere with the SECURE keyword. These are sign posts to things you will need, or you at least need to understand why you aren't using them. Update all your nuget packages which have security patches. Use an Orm. If you already have an account management system go through the account and user controllers thoroughly to understand if you have broken authentication or session management. Check all of the controllers have the appropriate authorisation and role tags applied to them. There is a  unit test which checks all of your post /put/delete methods have validate anti forgery token applied. Check your post methods don't allow overposting and specify the fields which can be updated. Hope this helps. John

**Comment by arc95** [comment]
Hi @johnstaveley. I've applied all the `SECURE:` items to my app, with the exception of public key pinning, which I found could brick a site if not done right or if the cert expires. 

Now I'm wondering about `AppSensor` and if it's required. We're adding the `[Bind]` attribute to all POSTs, use Entity Framework to minimize AQL injection attacks, and have the same validation applied server-side as client.

Also, do you know some free online security evaluation tools for sites that you recommend? I saw this one from OWASP: http://www.zaproxy.org/. Thanks.

**Comment by johnstaveley** [comment]
Hi, appSensor is about logging if anyone has _tried_ to bypass your controls and attempted CSRF, form overposting, incomplete form submission which are usual attacks. This is work in progress as the next stage would then be to block or sign out a user making such an attack, making their probing of the application that much more difficult. So feel free to leave it and check back when I have completed the work.
